spring:
  application:
    name: donor-api
  profiles:
    active: docker

  datasource:
    url: jdbc:postgresql://db:5432/donation
    username: postgres
    password: mdsoln
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10

logging:
  level:
    root: info
    com.donorapi: debug

