#version: "3.9"

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdsoln
      POSTGRES_DB: nutrition
    ports:
      - "5432:5432"
    networks:
      - backend_network

  backend:
    #build: .
    image: mdsoln/smart-nutrition-tool-apis:latest
    container_name: smart-nutrition-tool-apis
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nutrition
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mdsoln
      #SPRING_PROFILES_ACTIVE: docker
    networks:
      - backend_network

networks:
  backend_network:
